# Generated by Django 5.2.8 on 2025-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_unique_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
